/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  InnerComponent as InnerComponent
} from './components/inner-component/inner-component';

declare global {
  interface HTMLInnerComponentElement extends InnerComponent, HTMLElement {
  }
  var HTMLInnerComponentElement: {
    prototype: HTMLInnerComponentElement;
    new (): HTMLInnerComponentElement;
  };
  interface HTMLElementTagNameMap {
    "inner-component": HTMLInnerComponentElement;
  }
  interface ElementTagNameMap {
    "inner-component": HTMLInnerComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "inner-component": JSXElements.InnerComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface InnerComponentAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  MyComponent as MyComponent
} from './components/my-component/my-component';

declare global {
  interface HTMLMyComponentElement extends MyComponent, HTMLElement {
  }
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    "my-component": HTMLMyComponentElement;
  }
  interface ElementTagNameMap {
    "my-component": HTMLMyComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-component": JSXElements.MyComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface MyComponentAttributes extends HTMLAttributes {
      first?: string;
      last?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
