/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  InnerNoshadow as InnerNoshadow
} from './components/inner-noshadow/inner-noshadow';

declare global {
  interface HTMLInnerNoshadowElement extends InnerNoshadow, HTMLElement {
  }
  var HTMLInnerNoshadowElement: {
    prototype: HTMLInnerNoshadowElement;
    new (): HTMLInnerNoshadowElement;
  };
  interface HTMLElementTagNameMap {
    "inner-noshadow": HTMLInnerNoshadowElement;
  }
  interface ElementTagNameMap {
    "inner-noshadow": HTMLInnerNoshadowElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "inner-noshadow": JSXElements.InnerNoshadowAttributes;
    }
  }
  namespace JSXElements {
    export interface InnerNoshadowAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  InnerShadow as InnerShadow
} from './components/inner-shadow/inner-shadow';

declare global {
  interface HTMLInnerShadowElement extends InnerShadow, HTMLElement {
  }
  var HTMLInnerShadowElement: {
    prototype: HTMLInnerShadowElement;
    new (): HTMLInnerShadowElement;
  };
  interface HTMLElementTagNameMap {
    "inner-shadow": HTMLInnerShadowElement;
  }
  interface ElementTagNameMap {
    "inner-shadow": HTMLInnerShadowElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "inner-shadow": JSXElements.InnerShadowAttributes;
    }
  }
  namespace JSXElements {
    export interface InnerShadowAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  MyComponent as MyComponent
} from './components/my-component/my-component';

declare global {
  interface HTMLMyComponentElement extends MyComponent, HTMLElement {
  }
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    "my-component": HTMLMyComponentElement;
  }
  interface ElementTagNameMap {
    "my-component": HTMLMyComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-component": JSXElements.MyComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface MyComponentAttributes extends HTMLAttributes {
      first?: string;
      last?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
